#!/usr/bin/env bash

WIDGET_DIR="$HOME/.config/bspwm/plugins/eww"

	case "$1" in
		--menu)
			rofi -show drun -theme $HOME/.config/bspwm/scripts/styles/Launcher.rasi
			;; 
		--terminal)
			alacritty
			;;
		--floating)
			alacritty --class FloaTerm,Alacritty -o window.dimensions.lines=22 window.dimensions.columns=90
			;;
		--update)
			alacritty --hold --class FloaTerm,Alacritty -o window.dimensions.lines=22 window.dimensions.columns=90 -e Updates --update-system
			;;
		--checkupdates)
			alacritty --hold --class Updating,Alacritty -o window.dimensions.lines=22 window.dimensions.columns=47 -e Updates --print-updates
			;;
		--ranger)
			alacritty --class FloaTerm,Alacritty -o window.dimensions.lines=14 window.dimensions.columns=90 -e ranger
			;;
		--nvim)
			alacritty -e lvim
			;;
		--fetch)
			alacritty --hold --class FloaTerm,Alacritty -o window.dimensions.lines=26 window.dimensions.columns=40 -e ~/.local/bin/sysfetch;;
		# Apps
		--filemanager)
			nautilus
			;;
		--browser)
			firefox
			;;
		--editor)
			geany
			;;
		--telegram)
			telegram-desktop
			;;
		--whats)
			whatsapp-nativefier --disable-gpu
			;;
		--soundcontrol)
			pavucontrol
			;;
		# Eww Widgets
		--powermenu)
			eww -c "$WIDGET_DIR" open --toggle powermenu
			;;
		--usercard)
			eww -c "$WIDGET_DIR" open --toggle launchermenu
			;;
		--player)
			eww -c "$WIDGET_DIR" open --toggle music
			;;
		--calendar)
			eww -c "$WIDGET_DIR" open --toggle date
			;;
		*)
			echo "Invalid Option"
			;;
	esac
