#!/usr/bin/env bash
exec 2> /tmp/bspwm.log
set -x

PATH="$HOME/.config/bspwm/scripts:$PATH"

# Default one monitor with six workspaces
	for monitor in "$(xrandr -q | grep -w 'connected' | cut -d' ' -f1)"; do
		bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6'
	done
	
# Configure settings of bspwm
bspc config external_rules_command "$HOME"/.config/bspwm/scripts/system/ExternalRules
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 5
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2	resize_side
bspc config pointer_action3 resize_corner
bspc rule -a scratch sticky=on state=floating focus=on
bspc config window_gap 6
bspc config split_ratio 0.51
bspc config border_width 0
bspc config top_padding 56
bspc config bottom_padding 2
bspc config left_padding 2
bspc config right_padding 2
bspc config normal_border_color "#414868"
bspc config active_border_color "#c0caf5"
bspc config focused_border_color "#bb9af7"
bspc config presel_feedback_color "#7aa2f7"

# Set sysvars for polybar.
. "$HOME"/.config/bspwm/scripts/system/SetSysVars

# Verify and kill all process before run same.
processes=("sxhkd" "polybar" "stalonetray" "dunst" "eww.*bar")
	for process in "${processes[@]}"; do
		if pgrep -f "$process"; then
			pkill -9 -f "$process" > /dev/null; sleep 0.1
		fi
	done

# Launch polybar in all monitors.	
	for mon in $(polybar --list-monitors | cut -d":" -f1); do
		MONITOR=$mon polybar -q bar -c "$HOME"/.config/bspwm/plugins/polybar/config.ini &
	done

# dps resolvo sbct
sxhkd -c "$HOME"/.config/bspwm/plugins/sxhkd/sxhkdrc &

stalonetray -c "$HOME"/.config/bspwm/plugins/stalonetray/stalonetrayrc & sleep 0.1 && xdo hide -N stalonetray && touch "/tmp/syshide.lock"

dunst -config "$HOME"/.config/bspwm/plugins/dunst/dunstrc &

feh -z --no-fehbg --bg-fill "$HOME"/.config/bspwm/assets/walls/01.webp
betterlockscreen -u "$HOME"/.config/bspwm/assets/walls/01.webp

pidof -q eww || { eww -c "$HOME"/.config/bspwm/plugins/eww/eww daemon & }
pidof -q picom || { picom -b --animations --animation-window-mass 0.5 --animation-for-open-window zoom --animation-stiffness 350 --config "$HOME"/.config/bspwm/plugins/picom/picom.conf & }
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

xsetroot -cursor_name left_ptr
